### ISSUE TITLE
[Elcodi] Fix static::$kernel usage in our WebTestCase

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#1017]
Due to [this issue from Symfony](https://github.com/symfony/symfony/issues/16840), we should try to fix this from our side (bad usage of static::$kernel property).

Some tips:
- Use internal kernel usage with another property name

Actions to do:
- [x] Check and Fix issue in Elcodi
- [x] Resolve and Close Symfony issue with some explanation and feedback

**Comment by EmanueleMinotto** [comment]
Part of this problem is related to https://github.com/mmoreram/SimpleDoctrineMapping/blob/master/Configurator/LocatorConfigurator.php#L39

Could be resolved by doing https://github.com/elcodi/elcodi/issues/992
