### ISSUE TITLE
Discount over whole category

### ISSUE THREAD

**Issue by fjavier-moreno** [elcodi/elcodi#1040]
It would be very useful to be able to apply discounts by category.

Thanks in advance!

**Comment by mmoreram** [comment]
This is already managed by the new Coupon Query Language

* [CQL commit](https://github.com/elcodi/elcodi/commit/102208f6069e6e546223fc6d2bb05d1b546ac34d)
* [Documentation](http://elcodi.io/docs/book/coupon-architecture/#coupon-types)

**Comment by fjavier-moreno** [comment]
Great!!

Thx!!
