### ISSUE TITLE
composer php restricted to ^5.4 or ^7.0

### ISSUE THREAD

**Issue by gunderjt** [elcodi/elcodi#1074]
Hello all,

I tried to install Elcodi via composer I receive an error that says that my php (v5.6.9) is not supported by this package and it tries to install a really old version by default.  The documentation states that php 5.4 or greater is required, however, the composer file states that `"php": "^5.4|^7.0"` is required, [Which means](https://getcomposer.org/doc/articles/versions.md#caret) that only php versions 5.4.* and 7.0.* are allowed.

So is it really on 5.4 or is 5.4 the minimum? In the latter case the composer file should read `"php": ">5.4|^7.0"`, if I'm not mistaken

Thanks

**Comment by EmanueleMinotto** [comment]
Hi @gunderjt, the [caret operator](https://getcomposer.org/doc/articles/versions.md#caret) means (in this case) that the PHP versions allowed are 5.4, 5.5, 5.6 and 7.0.

Can you attach the error that Composer gives you, please?

**Comment by gunderjt** [comment]
My mistake.  Symphony automatically set config.platform.php to a 5.3.9 on my test project leading to the error.  Once I removed it I was able to install elcodi.  Sorry for the trouble
