### ISSUE TITLE
Refactor ReferralProgramManager

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#209]
ReferralProgramManager construct method has 12 dependencies. Too much.

Refactor this service.

**Comment by xphere** [comment]
With new `ObjectDirector`s some of them may be removed, but logic inside this class is too heavy. I think this should be split in more services. Even we talked to make this a plugin, IIRC.

**Comment by mmoreram** [comment]
There is a new issue to remove the module.
