### ISSUE TITLE
[MediaBundle] GD resize adapter

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#221]
* Create GD resize adapter and set it as default one
* Add gd as suggestion in composer

**Comment by xphere** [comment]
There are many other general purpose image libraries that we can support instead, like [Imagine](https://github.com/avalanche123/Imagine), that we should take into account. This one even has a bundle to select between rendering engines, so the switch between GD and Imagick should be absurdly easy.

**Comment by alch** [comment]
@xphere +1

**Comment by mmoreram** [comment]
Okay, we can take a look at Imagine :)

**Comment by mmoreram** [comment]
Closing this issue. GD adapter is already installed, and if Imagine is intended to be done, then will deserve it's own issue :)
