### ISSUE TITLE
[Currency] Add conversion truncate

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#232]
When we convert between currencies, we can reach this scenario.
```
1.224 = 1.22
2.448 = 2.45
```
and this introduces inconsistency. 

We should manage this scenarios and add some disclaimers with configurable values.

**Comment by xphere** [comment]
Any idea about this? /cc @elcodi/deciders

**Comment by mmoreram** [comment]
I add this issue for v1.1. Let's solve that or close it.
