### ISSUE TITLE
[RFC] Take in account the .class params removal in SF3.0

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#270]
https://github.com/symfony/symfony/issues/11881

**Comment by xphere** [comment]
Maybe we can add some extra methods in `AbstractExtension` or [a new `CompilerPass` for class overriding](http://symfony.com/doc/current/cookbook/bundles/override.html#services-configuration), since this will be the preferred way to do it in symfony 3.0.

**Comment by mmoreram** [comment]
So... it seems we will have to do this.

Adding in the new `v1` roadmap.

**Comment by cordoval** [comment]
@mmoreram please change this ticket out of RFC since it was decided already.

**Comment by cordoval** [comment]
you can close this @mmoreram right?

**Comment by cordoval** [comment]
ping @mmoreram we can close i think

**Comment by xphere** [comment]
I'm leaving this open as a remainder until RC-1 is ready to be merged. Thanks @cordoval

**Comment by mmoreram** [comment]
This issue was solved some time ago :)
Thanks!
