### ISSUE TITLE
[Comment] Parsedown: GitHub flavored markdown adapter

### ISSUE THREAD

**Issue by alch** [elcodi/elcodi#276]
We should implement a GitHub comment [adapter](https://github.com/elcodi/Comment/tree/master/Adapter/Parser) to allow on-the-fly GH flavored markdown rendering via API.

~~See https://developer.github.com/v3/markdown/~~

The adaptee should be https://github.com/erusev/parsedown

**Comment by xphere** [comment]
This may be irrelevant now since the last update of the `Comment` component.

**Comment by mmoreram** [comment]
Closing it.
Thanks :)
