### ISSUE TITLE
Testing faster

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#310]
Passing all the tests is quite slow, so I will give [fastest](http://welcometothebundle.com/speedup-symfony-functional-tests-phpunit/) a try.
Also, [grouping](https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.group) would be a nice addition to our tests.

**Comment by xphere** [comment]
Just discussed with @mmoreram to get some of the ideas from LiipFunctionalTestBundle, specially the sqlite fixture optimization would be nice. Would be nice to hear some more opinions.

**Comment by xphere** [comment]
Irrelevant since the development of `FixtureBooster` and following the ["Running the Test suite" documentation](https://github.com/elcodi/docs/blob/5821ac02aab8c9e07d59a131aba40270a0af8256/cookbook/caveats/test-suite.md)

**Comment by cordoval** [comment]
I actually think that the tests we have can be dramatically improved.
