### ISSUE TITLE
[User] AuthenticationSuccessEventListener name

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#324]
I wonder if `Elcodi/Component/User/EventListener/AuthenticationSuccessEventListener` is the best name for a listener. Sure, it reacts to `AuthenticationSuccess` events, but we're missing the point on the work the listener does. In this case, moving the `Cart` from anonymous user to the authenticated one. Maybe `UpdateCartUserListener`? `PromoteCartUserListener`? I don't know.

PD: I just ran into this one, I don't know if there are more like this.
PPD: Also I don't like listeners to be too concerned of their own "listener" nature, but that's another unrelated issue.

**Comment by xphere** [comment]
This is something we should discuss and start renaming (or not)

**Comment by cordoval** [comment]
@mmoreram this can be closed as it has been merged
