### ISSUE TITLE
Start all the internationalization of the Elcodi core

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#328]
Create all needed file to make all the packages compatible with i18n. Important! We should create an standard (check Symfony standard) for the naming of the translatable placeholders.

Make sure all typos are translated or support translation. Also create default English translation with current data

* Exception messages
* Templates (if exists)
* Output messages

**Comment by cordoval** [comment]
@mmoreram i don't think we should translate exception messages, not even as a comprehension layer. If i want to go to where the exception happens it will be a second level of indirection, not good thing to have as a developer.

@mmoreram regarding this task I am not sure what exactly entail (need a checklist of items for course of action) and also let's keep in mind the changes for internationalization regarding symfony as well (i think there were some in the past months).

**Comment by hacfi** [comment]
I agree with @cordoval to not translate exception messages - this will just be a mess!
