### ISSUE TITLE
[RFC] Create documentation skeleton

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#329]
The moment has arrived. Let's document.

I'll ping all interested people because would be nice to have some external feedback :) // ping @elcodi/reviewers @elcodi/owners 

We should create an skeleton before creating new issues.

* What is Elcodi
* Bundles and Components - What and when we should use them
* Starting with... ( Easy recipes for early starters )
    * Cart
    * ...
* Expertizing in ... ( Detailed recipes for advanced adopters )
    * Cart
    * ...
* Bamboo as implementation
* Some use cases

**Comment by xphere** [comment]
This is irrelevant now we have [elcodi/docs](//github.com/elcodi/docs)
