### ISSUE TITLE
[CustomerWrapper] Consolidate getCustomer() and loadCustomer()

### ISSUE THREAD

**Issue by alch** [elcodi/elcodi#357]
In `CustomerWrapper` there are two similar methods:

`CustomerWrapper::getCustomer()`
`CustomerWrapper::loadCustomer()`

The first one is a simple getter, the second checks if the `Customer` has already been set in the wrapper, sets it and returns it. In such a wrapper, the `getCustomer` method looks redundant and dangerous, since it can return `null`

**Comment by xphere** [comment]
Closing in favor of #368
