### ISSUE TITLE
[RFC] Scrutinizer fixes

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#366]
I just looked at [scrutinizer in out last merge](https://scrutinizer-ci.com/g/elcodi/elcodi/inspections/7d7b06c9-1153-4b2c-ab6f-b864eeaabac1) and see 496 issues. Shouldn't we address this? That would be piece of cake…

**Comment by xphere** [comment]
As Scrutinizer is being too picky, maybe that's a NO for now.
Closing in an hour if nobody rises a flag.

**Comment by hacfi** [comment]
@xphere I agree that Scrutinizer is too picky. At some point we should check if there are actual errors/optimizations but I don’t consider this urgent.

**Comment by xphere** [comment]
Yes, maybe there are some actions to be taken in the future. Just moving to 1.0 will do.

**Comment by hacfi** [comment]
After having a quick glance I only found one "mistake" https://github.com/mmoreram/SimpleDoctrineMapping/blob/master/CompilerPass/Abstracts/AbstractMappingCompilerPass.php#L69
should be
```php
     * @param boolean|string   $enable                Entity mapping must be included
```

**Comment by cordoval** [comment]
I took care of several and send PRs. @hacfi i have also opened https://github.com/mmoreram/SimpleDoctrineMapping/pull/18 since it is inside another repository.
