### ISSUE TITLE
[RFC] Wrapper Interface

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#368]
Let's discuss about how a Wrapper should be defined, and let's adapt all our implementations. Please, discuss here. Once we have a clean definition, we could edit this issue with the final result.

[EDIT]

< WrapperInterface >
* load - Loads all data if is not saved locally yet, and save locally all needed structure. Return result.
* reload - Clean local data and load again. Return result.

**Comment by xphere** [comment]
Shall we put this "on hold" until 1.0 is ready?

**Comment by cordoval** [comment]
this has little context outside your internal discussions, could you explain a bit more @mmoreram ? thanks

**Comment by xphere** [comment]
I do not agree. This wrapper definition may help simplify some services, like the ones having hardcoded caches, as [PluginManager](https://github.com/elcodi/elcodi/blob/0d59379fec3c5827b16a8f4251f40aeb943c2468/src/Elcodi/Component/Plugin/Services/PluginManager.php) or [MenuManager](https://github.com/elcodi/elcodi/blob/4702c94a1d232544a0776aed17a43b263ae66813/src/Elcodi/Component/Menu/Services/MenuManager.php).

We can make this services dependant on a single `Wrapper` (or `Proxy`) which can be anything compliant with our interface, from a cache layer, to a final implementation doing the real work. This layers can stack as many as we need and be configurable in compilation time: Cached in memory, getting from redis, loading from configuration, querying to a database…

**Comment by cordoval** [comment]
now that I see some directions I am opposed to wrapping several services into one bag. I don't see much value in terms of SOLID.
