### ISSUE TITLE
[Page] Multiple implementations of `RouteLoader`

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#389]
Now, `RouteLoader` is implemented by `PageRouterSimpleLoader` but will be interesting to add other implementations, like a static one, warmed up in compilation time.

**Comment by cordoval** [comment]
@xphere can you please provide reasons for such those implementations? thnanks

**Comment by xphere** [comment]
Think about a static system, with no dynamic creation of pages, just the ones in the fixtures.
One may want to generate the paths statically, iterating over the pages at compilation time.
This should create a faster routing, since it'll be database independent in runtime.
