### ISSUE TITLE
[Geo] Zone[Country, State...]Member and Zone.orm.yml 

### ISSUE THREAD

**Issue by sfblaauw** [elcodi/elcodi#390]
Hi,
I'm trying to add new `Zone member` to a `Zone` using a collection form type but I have several problems:

1 - Symfony throw an exception because no arguments are added to, for example, `ZoneCountryMember`:

`Catchable Fatal Error: Argument 1 passed to Elcodi\Component\Geo\Entity\ZoneCountryMember::__construct() must implement interface Elcodi\Component\Geo\Entity\Interfaces\ZoneInterface,`

2 - Hardcoding `ZoneCountryMember` construct arguments to null, Symfony does not throw the first exception but throw's a new exception because no setters exist, in this case `setZone` and `setCountry`:

`Neither the property "country" nor one of the methods "addCountry()"/"removeCountry()", "setCountry()", "country()", "__set()" or "__call()" exist and have public access in class "Elcodi\Component\Geo\Entity\ZoneCountryMember"`

Maybe I am wrong but I think that the `Zone[Country, State...]Member` arguments has to be null and add setters to the `Zone[Country, State...]Member` models. If I am wrong please can you explain me why.

Also, in my point of view, `Zone.orm.yml` **members** has to have `cascade: [ "all" ]`

Thanks

**Comment by xphere** [comment]
Is this still relevant with the new location model?

**Comment by rogergros** [comment]
Ping @sfblaauw ?

**Comment by mmoreram** [comment]
No its not. Closing it.
