### ISSUE TITLE
[RFC] Remove all long service names and remove parameters

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#398]
Only work with short services names
To remove complexity and container size as well

**Comment by xphere** [comment]
Most of them have been addressed. May we close this?

**Comment by rogergros** [comment]
@mmoreram & @berny We have changes a lot of them, we could close this task and keep changing it on the go.

**Comment by mmoreram** [comment]
Great.

**Comment by xphere** [comment]
PS: @rogergros, it's a me, @xphere, not @​berny :metal:

**Comment by rogergros** [comment]
Woops :sweat_smile:
