### ISSUE TITLE
[RFC] Product translations forms

### ISSUE THREAD

**Issue by tonipinel** [elcodi/elcodi#432]
Now that we have the chance to translate the product name and description there are some grey areas that we need to define, about fallbacks and other issues.  Here is my proposal:

* Set one master language to the store
* Have the possibility to add another languages to the store (not to concrete products)
* At the product form will be tabs for each language but just the master language is required. If some language fields are empty, the master language will be shown

**Comment by mmoreram** [comment]
Fixed in #440 :)
