### ISSUE TITLE
Stock control simplify

### ISSUE THREAD

**Issue by tonipinel** [elcodi/elcodi#434]
To simplify the control of the stock, by default the stock should be -1 (infinite) and will be shown always as an input hidden in the product form.

 If you enable the stock control in the shop preferences, then the stock options will be editable in the product form.

**Comment by mmoreram** [comment]
From

**Comment by rogergros** [comment]
Current behavior:
Stock **disabled** on store setup:
- Not "no stock" messages is shown
- Not stock is "substracted" from the product when added to the cart

Stock is **Enabled** on store setup:
- "No stock" is shown when a product has no stock and the product can't be added to the cart
- The stock is "substracted" from the product when added to the cart

Can we close this task @tonipinel  ?

**Comment by tonipinel** [comment]
It's ok!
