### ISSUE TITLE
[RFC] Configuration must play fair with Symfony ecosystem

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#447]
As we'll surely coexist with multiple third party bundles in a project, we need to be fair with other libraries by namespacing global functions with `elcodi_`.

This is the case, for example, of `getConfiguration` function in the twig extension for the `Configuration` component. I suggest to rename it to `elcodi_config` or `elcodi_get_config`.

**Comment by rogergros** [comment]
Makes sense for me
