### ISSUE TITLE
Register `elcodi_config` in ExpressionLanguage

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#448]
With the new [extension providers](http://symfony.com/doc/current/components/expression_language/extending.html#using-expression-providers) of ExpressionLanguage, we can register our own `elcodi_config` function and use this as a replacement for `@=service("elcodi.configuration_manager").getParameter('namespace.key')`, so we can only write `@=elcodi_config('namespace.key')` instead.

**Comment by mmoreram** [comment]
Hmmm, @alch and me have tried to find how to do that... and it is not possible? Hmmm, let's keep trying it :|

**Comment by xphere** [comment]
Well, not an easypick anymore, not until https://github.com/symfony/symfony/issues/13267 is fixed.

**Comment by xphere** [comment]
Fixed in https://github.com/symfony/symfony/commit/8425e4d9d011d34a0e3527dc7365602727b6a818, would be applyable in v2.6.2
