### ISSUE TITLE
[RFC] Rename of Configuration

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#464]
I really think this component name clashes with the concept of configure application in symfony and surely this will add trouble to other devs. Is this annoying to someone else?

I would like to easy diferentiate both ideas, so my suggestion is to change `Configuration` name. I propose `Settings`, since it's a common trope (in videogames, for example).

Any ideas?

**Comment by xphere** [comment]
Can we accept/reject/discuss this one? We're stocking on RFC's, but not solving them. /ping @elcodi/owners

**Comment by cordoval** [comment]
:+1: for closing this. This is what namespaces are for to avoid collision. If it is configuration it is such.

**Comment by mmoreram** [comment]
Hmmm... I'm not sure about this...
@xphere Let's discuss this tomorrow :)

**Comment by cordoval** [comment]
The same reasoning applies to Symfony Configuration class. I found yesterday that these are even related so all the more things make sense and there is no conflict. I am not going to raise this argument again. So from now on I am :+1: either way. :older_man:

**Comment by hacfi** [comment]
I like `Settings`. An alternative would be `Setup` but I like it less because it could be associated with Installation.

**Comment by mmoreram** [comment]
Closing this issue.
Configuration is not used anymore.
