### ISSUE TITLE
Create only one command for all sitemaps

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#468]
Remove the creation of one-command-per-sitemap and create one single command with a --name paremeter

**Comment by mickaelandrieu** [comment]
Related to this Command ? => https://github.com/elcodi/elcodi/blob/master/src/Elcodi/Component/Sitemap/Command/DumpSitemapCommand.php

Did you suggest to add another command with a specific ``name`` parameter or to improve the current implementation ?

**Comment by cordoval** [comment]
bump @mmoreram

**Comment by cordoval** [comment]
bump @mmoreram

**Comment by xphere** [comment]
Fixed in https://github.com/elcodi/elcodi/pull/712
