### ISSUE TITLE
[EntityTranslator] Optimize redis gets

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#476]
Get all translatable fields of an entity in a single request

**Comment by cordoval** [comment]
not sure whether this is related to elcodi or to bamboo, please move outside if the latter is true.
also if the latter is true, could you please expand on the actionables for this one?

**Comment by cordoval** [comment]
How am i doing @mmoreram in #743

**Comment by mmoreram** [comment]
This issue is simply that, if you start fetching an entity, if you know the fields you have to fetch (you do indeed), then is better to fetch all fields in a single redis get.
