### ISSUE TITLE
[Product] Logical error with ElcodiProductStock

### ISSUE THREAD

**Issue by hacfi** [elcodi/elcodi#581]
I think I found a logical error:
https://github.com/elcodi/elcodi/blob/master/src/Elcodi/Component/Product/Services/ProductCollectionProvider.php#L126-144
`$infiniteStockIsNull = is_null(ElcodiProductStock::INFINITE_STOCK);` will always be true. It doesn’t make sense to check a constant for a value. I double-checked and this value also never changed so either $infiniteStockIsNull becomes a method argument or remove it at all!?

**Comment by mmoreram** [comment]
Lol, absolutely ... Thanks for the report :)

**Comment by hacfi** [comment]
You’re welcome! I’m getting more involved again soon!

**Comment by hacfi** [comment]
Closing as #636 resolved this
