### ISSUE TITLE
French translations are missing

### ISSUE THREAD

**Issue by mickaelandrieu** [elcodi/elcodi#585]
Hi everyone,

I want to help, can you tell me what steps I need to follow to add French support in elcodi/bamboo product?

I will probably do it saturday on my own "Elcodi's day Paris edition" (only 1 attendee :dancer: , but a very motivated attendee !).

**Comment by xphere** [comment]
Hi @mickaelandrieu,

The project is like any other symfony2 application, so just search every `messages.en.yml` in the project, copy it to `messages.fr.yml` and start translating this one. Then change your locale to `fr` in `parameters.yml`.

The only thing that's special to this project is that your local language must be active in the `Language` entity, so update this manually in your database and all should be fine. (This will be easier soon with an UI in the admin)

By the way, this issue should be in [elcodi/bamboo](//github.com/elcodi/bamboo).

Thanks for the motivation! Have fun! :dancer:
