### ISSUE TITLE
ImageExtension::randomizeBaseUrls not so random

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#621]
The distribution of current `randomizeBaseUrls` in `ImageExtension` is quite poor and scales horribly, check [this test](http://3v4l.org/FLaC5) with [current implementation](https://github.com/elcodi/elcodi/blob/ed36afb74780c2d4d1b80f496d2dc20dea7cd9f5/src/Elcodi/Component/Media/Twig/ImageExtension.php#L184).

There are some issues:
- `0` is never picked.
- `1` and `2` are more likely to be chosen (like 10:1 and 3:1 respectively)
- Multiple calls for same `path`, can return different shard.

I'd remove the `substr` call and do just `mt_rand(0, count($hostNames))`

**Comment by javiereguiluz** [comment]
I'd recommend you to not pick one base URL randomly. It's considered better to pick a base URL in a deterministic way based on the given asset. This simplifies asset caching. [Here](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Asset/UrlPackage.php#L107-120) you can see this approach in the [new Symfony Asset component](https://github.com/symfony/asset):

```php
protected function chooseBaseUrl($path)
{
    return fmod(hexdec(substr(hash('sha256', $path), 0, 10)), count($this->baseUrls));
}
```

**Comment by alch** [comment]
I'd solve the problem in the hard way by *removing the pseudo-random url* altogether and the `randomizeBaseUrls` method. Today it's better to rely on [SPDY multiplexing](http://en.wikipedia.org/wiki/SPDY) than trick the browser into parallel downloads using different hostnames.

A side note: I **really** don't remember why I put that `substr`

**Comment by cordoval** [comment]
@alch don't worry it will not matter anymore, i like your approach on simplicity

**Comment by mmoreram** [comment]
@alch SPDY is dead XD

**Comment by mmoreram** [comment]
@cordoval @alch @xphere So... this *random* generation is removed? Is not random anymore?

**Comment by cordoval** [comment]
@mmoreram SPDY is not dead

**Comment by alch** [comment]
Some good soul can remove the `randomizeBaseUrls` method? This will just fix the issue :dancer:

**Comment by cordoval** [comment]
@alch did you not notice the PR i sent and it is referenced by github in this thread? please mind those PRs and notifications. Please. Thanks

**Comment by cordoval** [comment]
#700

**Comment by alch** [comment]
@cordoval good boy :+1:
