### ISSUE TITLE
Geo Component - Location entity weird behaviour

### ISSUE THREAD

**Issue by claretcrab** [elcodi/elcodi#628]
Hi,

I did a php app/console doctrine:cache:clear-metadata and then php app/console doctrine:schema:update --dump-sql

Now table location_inheritance has changed to location_locationinterface (and column names changed too), why? In Location.orm.yml has location_inheritance as name

**Comment by hacfi** [comment]
@claretcrab Should be fixed now (see #629 and #630)

**Comment by claretcrab** [comment]
:thumbsup:
