### ISSUE TITLE
Visible Tracking pixels in chrome and ie

### ISSUE THREAD

**Issue by claretcrab** [elcodi/elcodi#634]
related to  added display none to tracking pixels #587

**Comment by cordoval** [comment]
can you please elaborate further @claretcrab ?

**Comment by claretcrab** [comment]
Sure, it's related to this old PR https://github.com/elcodi/elcodi/pull/587/files

It's fixed for firefox but chrome and iexplorer, I tried with:

* style="position:absolute; visibility:hidden"
* style="display:none"
* width="0" height="0"

but aren't enough to avoid rendering those pixels

**Comment by mmoreram** [comment]
ping @tonipinel

**Comment by cordoval** [comment]
I think they are not visible in any browser, the only thing is that they currently return 404's but i am looking into this now.

**Comment by cordoval** [comment]
#709 solves the issue of tracking pixel display. The loading problem is totally apart.

**Comment by cordoval** [comment]
ping @mmoreram close this ticket as it has been solved
