### ISSUE TITLE
Event payment.order.fail is never dispatched

### ISSUE THREAD

**Issue by claretcrab** [elcodi/elcodi#637]
When there is an error in a payment and you're redirected to payment/fail/order/{id}, the event payment.order.fail is never dispatched.

I think it would be useful to suscribe to this event in order to trigger some actions.

**Comment by xphere** [comment]
Why was this closed so early? A comment would surely help :wink:

**Comment by claretcrab** [comment]
:D Because I think it was my fault, I was doing a bad testing with stripe payment bundle, I assume that works fine with paymill and paypal.
