### ISSUE TITLE
Add recipes

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#645]
Architecture
- [ ] Bundles
- [ ] Components

Elcodi in deep
- [ ] Factories
- [ ] Repositories
- [ ] ObjectManagers
- [ ] Directors
- [ ] EventDispatchers
- [ ] EventListeners
- [ ] Controllers
- [ ] Commands
- [ ] Services
- [ ] Wrappers

Testing
- [ ] Unit tests
- [ ] Functional tests
- [ ] How to pass the tests

**Comment by cordoval** [comment]
what do you mean recipes? do you mean perhaps usage in the readme? :+1:

**Comment by xphere** [comment]
IMO, `README` should have basic usage documented. That's what https://github.com/elcodi/elcodi/issues/648 is for.

Recipes are more like a common usecase and how to solve it. A pattern involving more than one component/bundle or common knowledge about them.

**Comment by cordoval** [comment]
These perhaps should be called cookbooks.

**Comment by xphere** [comment]
Well, isn't a cookbook made from recipes? :smile:

**Comment by cordoval** [comment]
correct, but since it is a collection, it is a cookbook :+1:

**Comment by cordoval** [comment]
we should add that locally one has to remove rm -rf /tmp/*.backup.database files in order to recreate the fixtures on functional tests without ties to the past.

**Comment by cordoval** [comment]
This ticket could be moved to documentation repo?

**Comment by xphere** [comment]
@cordoval :+1: this should be moved to elcodi/docs IMO.

**Comment by mmoreram** [comment]
@xphere ok
