### ISSUE TITLE
[ReferralProgram] Remove ReferralProgramBundle

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#651]
This bundle needs some love, and will be a great opportunity for refactor it and add it as a plugin.

**Comment by mmoreram** [comment]
https://github.com/elcodi/elcodi/pull/655

**Comment by cordoval** [comment]
why this is not closed if #655 was already merged?

**Comment by cordoval** [comment]
ping @mmoreram ?

**Comment by xphere** [comment]
Already fixed, thanks @cordoval
