### ISSUE TITLE
Some replacements of Bundles

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#656]
We could create a new organization (already created, for if the flies) called friends-of-elcodi, with non-ecommerce-related packages

FixturesBoosterBundle
StateTransitionMachine
* Component
* Bundle
EntityTranslationBundle
* Component
* Bundle

Then, for the EntityTranslationBundle we could create a Bridge, to make it usable in Elcodi environment.

**Comment by cordoval** [comment]
notice that keeping in the same vendor name even though not related to ecommerce gives visibility to the package. If you think another vendor name can make it well, I barely remember other vendors even though there are some good names like league or such that stick. :+1: for keeping the same vendor, just decouple them into repos and register via packagist.

**Comment by mmoreram** [comment]
@cordoval Agree with you... but for example the EntityTranslatorBundle should be in a separated Organization. Why? Well, is not related to Elcodi indeed, even if has been developed by us while doing Elcodi stuff, and because can be used in any Symfony Project.

Same with FixturesBoosterBundle, is just an add-on for tests, no matter the topic of the project. I am afraid that if we use the trademark Elcodi for distributing these packages, people will associate them all with E-commerce, even if they have nothing to do with that.

What do U think @elcodi/owners ?

**Comment by cordoval** [comment]
a company vendor on github does not mean that it all ties together, but i understand your concern. I am either way a :+1:

**Comment by xphere** [comment]
I like the `friends-of-` prefix, but I think it relates more to "libraries I can add to Elcodi" than to "libraries made from Elcodi people that can be used in any project".

About using the company vendor, I think like @cordoval, this does not tie libraries together, but may be hard to see this.

I don't know, I don't have a good solution for this. I can think of a vendor like `elcodi-tech` or something like that, but this may have the same problems of the other options.

**Comment by alch** [comment]
How about **elcoders** ?

@mmoreram *for if the flies* :facepunch:

**Comment by hacfi** [comment]
I like the organization name `friends-of-elcodi` but those bundles should use the `Elcodi` namespace and `elcodi/` composer package name prefixes if you ask me.

**Comment by cordoval** [comment]
let's go with friends-of-el-codi , i am creating PRs to remove the three bundles/components now

**Comment by cordoval** [comment]
The namespace will just adapt as FriendsOfElCodi/....

**Comment by cordoval** [comment]
@mmoreram can you please transfer the repository to respective repo in https://github.com/friends-of-elcodi doing a split tree and then get the total history there too? tagged 0.5 so we can sync both ends? Thanks

**Comment by xphere** [comment]
What's the status of this one?

**Comment by cordoval** [comment]
yeah I am updating the PRs by parts but there are some that are already "a go", the fixtures booster bundle but i need @mmoreram's help to move things to other repos.
