### ISSUE TITLE
Remove all long-names in Elcodi

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#660]
Remove all long-formatted names in Elcodi and replace them all with short-formatted names.

**Comment by mmoreram** [comment]
Long-formatted names are ...
```
elcodi.core.coupon.entity.coupon
```

And we are transforming all to
```
elcodi.entity.coupon
```

**Comment by cordoval** [comment]
on it thank you

**Comment by mmoreram** [comment]
:)

**Comment by cordoval** [comment]
@mmoreram "elcodi.core.entity_translator.configuration" -> "elcodi.entity_translator.configuration" ?

**Comment by cordoval** [comment]
nvm PR ready

**Comment by cordoval** [comment]
@mmoreram this should be closed

**Comment by mmoreram** [comment]
@cordoval Ups, I did not see your message here... I will take a look.

**Comment by mmoreram** [comment]
Well, there are some names still in long mode. Closed PR is only the entities.

Answering to your question... 
"elcodi.core.entity_translator.configuration" -> "elcodi.configuration.entity_translator"

Tomorrow morning I will add a cookbook with the naming conventions :)

**Comment by cordoval** [comment]
where are the conventions @mmoreram ?

**Comment by mmoreram** [comment]
Oh, doing them right now XD

**Comment by mmoreram** [comment]
@cordoval First cook entries http://elcodi.io/docs/book/index.html

Please, tell me if you are interested in something special... and I add the cook entry.

**Comment by cordoval** [comment]
@mmoreram is actually the opposite :older_man: 
ok going to play with my daughter at the park but i will be back for more pounding

**Comment by mmoreram** [comment]
The opposite of what? XD

**Comment by xphere** [comment]
Is this fixed before those two merged PR?

**Comment by cordoval** [comment]
I think you mean "before -> after". I believe there are still some remainders out there but are a lot harder to spot.
