### ISSUE TITLE
remove? time and behaviors on entities

### ISSUE THREAD

**Issue by cordoval** [elcodi/elcodi#684]
currently we are using doctrine behaviors with lifecycles, can we remove this dependency?
the reason is that on DDD when replaying domain events these times will not be able to be set to the time they were originally created. I think is very possible just to handle this the regular way and therefore provide more flexibility to the app to be used in this context.

**Comment by mmoreram** [comment]
I don't really understand what do you want to remove. An example?

**Comment by cordoval** [comment]
It is very simple. Those @Gedmo annotations or lifecyclecallbacks, we will not use them. Instead we do things so we can replay also dates.

**Comment by cordoval** [comment]
I think we can discuss it on gitter better so closing.
