### ISSUE TITLE
What is the interest of [get/set]Dimensions of a product ?

### ISSUE THREAD

**Issue by mickaelandrieu** [elcodi/elcodi#687]
Hi,
as Product use DimensionsTrait which provide everything we need, I don't see the point with the [get/set]Dimensions method: the PHPDoc says this have to return *string*.

Should we consider it as a nice way to return a human readable dimensions for a product ?

For instance:
```php
<?php
// /Product/Smartphone.php
namespace MyShop\Product;

use Elcodi\Component\Product\Entity\Product;

class Smartphone extends Product
{
    const SMARTPHONE_PRODUCT = 'smartphone';

    public function __construct()
    {
        $this->type = self::SMARTPHONE_PRODUCT;
    }

    public function setType($type)
    {
        throw new \LogicException("You can't change type of a product");
    }

    public function getDimensions()
    {
        if (isset($this->height) && isset($this->width)) {
            return $this->getHeight().'cm x'.$this->getWidth().'cm';
        }

        throw new \LogicException("We can't found dimensions for this smartphone have no dimensions.");
    }
}
```

**Comment by mmoreram** [comment]
Well, yes, it has sense, but remember... Anemic model. If you want to do this, then you will need a service that will do exactly this :)

**Comment by mickaelandrieu** [comment]
I'm not so "in love" of services. For me the entities can contains business. When you make libraries like elcodi, you need to be anemic but in a real application this is not so bad to have part of your business constraints in your entities (imo).

**Comment by mmoreram** [comment]
Maybe. Both strategies are valid depending on your goals. Our goal is to make the project as flexible as possible, so we have an absolute strategy of anemic model and rich service layer.

**Comment by mickaelandrieu** [comment]
Thanks for answer, closed :)
