### ISSUE TITLE
Attribute entity should have a constructor

### ISSUE THREAD

**Issue by mickaelandrieu** [elcodi/elcodi#688]
Let's say I want to sell iphones (because Yes, I want to win a lot of money :) ).

For an iphone6, I can sell many colors and memory size of a same product. I take a look to the Variant entity provided, but afaik this wont allow me to do that.

What I want to do:

```php
<?php
// /index.php
require_once('./vendor/autoload.php');

$apple = new Elcodi\Component\Product\Entity\Manufacturer();

// new attribute => color
$color = new Elcodi\Component\Attribute\Entity\Attribute();
$color->setName('Color');

// attribute values
$silver = new Elcodi\Component\Attribute\Entity\Value();
$silver->setValue('silver');

$gold = new Elcodi\Component\Attribute\Entity\Value();
$gold->setValue('gold');

$color->addValue($silver)
    ->addValue($gold)
;

$apple->setName('Apple inc.')
    ->setSlug('apple')
    ->setDescription('Apple Inc. is an American multinational that designs, develops, and sells consumer electronics, computer software, online services, and personal computers.')
;

$iphone6 = new MyShop\Product\Smartphone(); // which extends Elcodi\Component\Product\Entity\Product
$iphone6->setName('Iphone 6')
    ->setSku('iphone6_silver')
    ->setManufacturer($apple)
    ->addAttribute($color->setValue($silver))
;

$iphone6Variant = new Variant();
$iphone6Variant
    ->setSku('iphone6_gold')
    ->setOptions($color->setValue($gold));

var_dump($apple);
```

this will not work, because when I do ``$color->addValue($silver);`` I have an exception.
```
PHP Fatal error:  Call to a member function add() on a non-object in /home/mickael/Projets/phone-shop/vendor/elcodi/attribute/Entity/Attribute.php on line 108
```

I think we need to declare ``$values`` as a Collection.

**Comment by mmoreram** [comment]
Of course is not working.

http://elcodi.io/docs/cookbook/implementation/factory.html

All initialization of an entity must be placed inside a Factory. An entity will never know how to create itself. Given this strategy your entities are not coupled to `ArrayCollection` implementation, but to `Collection` interface ;)

:)

**Comment by mickaelandrieu** [comment]
But ... ```Because the factory dependencies need to be resolved, we must define the factory as a service.``` sounds weird to me outside of Symfony framework.

I will try with a factory, and I come back if I need help (I'm actualy try to write docs for Product component, so I may have some questions :D)

**Comment by mmoreram** [comment]
Well, if you want to use them outside Symfony, then you should instance the Factory by hand and request one entity instance. If you take a look on how a factory is instanced you will notice how easy is :)

**Comment by mickaelandrieu** [comment]
Updated:

**Comment by mmoreram** [comment]
Well, a factory is always related to your environment. You can emulate the factory behavior in your project by creating the `new` and by initializing your entity in your way.

A factory is a special way of doing in this project. Of course you can manage your entities however you want :)
