### ISSUE TITLE
doctrine and travis fix

### ISSUE THREAD

**Issue by cordoval** [elcodi/elcodi#694]
we should fix the asserts on exceptions as this broke the builds

**Comment by mmoreram** [comment]
Yes, something happened to GeoBundle after removal of BambooBundle.

Checkin'

**Comment by cordoval** [comment]
no, i think is totally unrelated to the removal

**Comment by mmoreram** [comment]
It's interesting...

https://travis-ci.org/elcodi/elcodi/builds/56893998 Only the prefer-lowest works... It means that an external dependency broke something, right?

**Comment by mmoreram** [comment]
I found the issue. Thanks Doctrine :)
