### ISSUE TITLE
[Menu] Add menu listeners

### ISSUE THREAD

**Issue by xphere** [elcodi/elcodi#711]
Now, in Bamboo, we're having logic in our `MenuController` to rework the menu and add, for example, more entries for plugins and additional data for orders. Even the `activeUrls` present in the component has no meaning until the `MenuController` does some magic to activate the menu.

All this logic can be splitted in listeners that will be dispatched when loading a menu, so we can have our `ActiveMenuListener` in the component, and others more specific in bamboo. Even shopery could benefit from this.

**Comment by cordoval** [comment]
have you checked on the menu 2.0 from knplabs if there is already infrastructure in place for this?

**Comment by cordoval** [comment]
so shopery is the business side of elcodi? interesting
