### ISSUE TITLE
Remove any ExtraFrameworkBundle dependency

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#725]
In some plugins (Wizard) we are using `@route` and `@method` annotations, adding as well a hard dependency in all package.

Options:

* We remove this dependency by adding a `routing.yml` file in the bundle, and adding such file in the config file.
* We add SensioExtraFramework as a `elcodi/elcodi` dependency **(NO)**

What do U think is the best one? XD

@rogergros

**Comment by cordoval** [comment]
:+1: LGTM :older_man:

**Comment by xphere** [comment]
I think here is missing the discussion we had yesterday evening with @rogergros where we decided to move plugins to `elcodi/bamboo` repository. Am I right?

**Comment by cordoval** [comment]
please close @mmoreram this ticket is not relevant anymore
