### ISSUE TITLE
please flush scrutinizer

### ISSUE THREAD

**Issue by cordoval** [elcodi/elcodi#733]
@mmoreram we don't need scrutinizer to run all the time, it makes runs painful, same as travis but travis is inevitable however scrutinizer can be run on the weekends only. Please turn it off.

**Comment by xphere** [comment]
Also travis is running two tasks for each new commit in every PR and branch, one named like `travis-ci/pr` and the other like `travis-ci/push`. Hopefully we can reduce this to just one task for each PR and branch master.

**Comment by cordoval** [comment]
@mmoreram closing now but i believe you saw our request, please just keep it in mind.

**Comment by sstok** [comment]
You can configure Travis (and scrutinizer) to only run on PR's, but this will also prevent running on the master branch. As way around you can create your own Webhook and when you are pushing to the master trigger the Travis-CI build manually.

Travis-CI: Setting -> Build pushes (off)
Scrutinizer: settings ->  Tracked Branches (master); others will be ignored automatically.

**Comment by cordoval** [comment]
nice trick @sstok cc @mmoreram I think travis overall is slow on FOSS, the enervating thing about things is that it fails or tests on our part are brittle. All I hope for is just consistency and narrowness if need be to get things running faster.
