### ISSUE TITLE
[Geo] Fix the types of LocationProviderInterface implementations

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#764]
There are some problem in both implementations, so same methods return different types, and this is a definition problem.

**Comment by cordoval** [comment]
This note is a bit cryptic, i checked and there is only once instance where the method returns LocationData instead of LocationData[] i think but giving more details on a ticket can greatly improve discussion. We can of course discovered it all but it is like hunting again for things.

**Comment by mmoreram** [comment]
Yes, sorry.

We have two implementations for `LocationProviderInterface`. One of them is intended to resolve some methods using the database directly, and the other one is an adapter for using the HTTP layer (API).

Both implementations should return exactly the same, and actually is not what happens - exactly what you say about `LocationData[]` or `LocationData` or `boolean`.

TIP: `in($id, array $ids)` has some problems

This task is about revising both implementations and document a little bit better those classes, in order to be easier using them.
