### ISSUE TITLE
Remove unnecessary setters in MoneyInterface, Money

### ISSUE THREAD

**Issue by amaneu** [elcodi/elcodi#801]
According to conversation on gitter:
https://gitter.im/elcodi/elcodi?at=555ca396bb71b5b2298676fc

Since `Money` is meant to be inmutable, no setters should be called on objects of that class, and it should not have any unnecessary setters :)

**Comment by mmoreram** [comment]
@amaneu Thanks :)

Closing this issue because was already solved!
