### ISSUE TITLE
[RFC] Elcodi minimum PHP version

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#855]
PHP is changing a lot. New version PHP7 is in alpha(~~beta~~) since a week ago, and, according to the PHP release and maintenance plan, PHP5.4 will die in 3 months, more or less.

http://php.net/supported-versions.php

Symfony3 minimum PHP version will be 5.5 so... given that Elcodi is going to be Symfony3 friendly (not based)... 

What version of PHP you suggest for Elcodi?
* Taking in account that we really want installations
* We want to do some push for new PHP versions in order to provide secured e-commerces

Any feedback will be appreciated.

**Comment by acasademont** [comment]
You already said it, 5.5 is the way to go! :dancer: 

PS: PHP7 is in the first alpha, not beta!

**Comment by mickaelandrieu** [comment]
Go for PHP >= 5.5 imo but keep as long as this dont require too much time a compatibility with 5.4 because "Hell no :'( " there is a lot of servers with PHP 5.4 (for example OVH)

**Comment by javiereguiluz** [comment]
I agree with @mickaelandrieu: hosting providers are not ready for 5.5/5.6. Besides, if you check out the [list of the main new feautres for PHP 5.5](http://php.net/manual/en/migration55.new-features.php):

  * `::class` is just a nice shortcut. We can live without it.
  * `finally` is a nice addition, but world won't end without using it.
  * array and string dereference: again nice additions but code works without them.
  * Generators: in my opinion this is the only really nice thing of PHP 5.5. I haven't seen them used in a large open source application. I've just seen some tutorials that use them for the sake of showing how do they work.

So in my opinion: you should target 5.5, but you should wait all you can before actually requiring 5.5.

**Comment by mmoreram** [comment]
@javiereguiluz @mickaelandrieu https://www.ovh.co.uk/g1207.how_to_configure_php_on_your_ovh_web_server_2014 Is currently supporting 5.6, but 5.5 I think will be the best option.

ping @alch

**Comment by xphere** [comment]
I'd vote for the law of least effort: our codebase right now is fully working in 5.3, so no need to change this. This broadens the range of potential users at no cost.

If we're talking about the forthcoming development of Elcodi, I'd go with 5.5 at least, for the same reasons as @mmoreram.

**Comment by davidguardiola** [comment]
I'm using PHP v5.5 on Amazon vps server.

**Comment by mmoreram** [comment]
We'll set, finally, PHP <=5.5 as the minimum PHP version for both Elcodi and Bamboo projects.

**Comment by alch** [comment]
I'd go for the 5.5 too

2015-06-23 12:11 GMT+02:00 David Guardiola <notifications@github.com>:

> I'm using PHP v5.5 on Amazon vps server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elcodi/elcodi/issues/855#issuecomment-114430371>.
>



-- 
*Aldo Chiecchia*
Partner & CTO
aldo.chiecchia@antaivb.com


*Antai Venture Builder*
C/Valencia 333 Bajos. 08009 Barcelona, Spain.
+34 902 734 050

*The international online & mobile venture builder.*
Barcelona  -  Paris  -  Santiago  -  Buenos Aires  -  Lima  -  Bogotá  -
 México D.F

**Comment by ostark** [comment]
>=5.6
All other PHP versions are not actively maintained today! Our thoughts: http://blog.fortrabbit.com/php-upgrade-path-5-4-5-6-7-0

**Comment by mmoreram** [comment]
I've thinking a lot about this issue, and after a lot of discussions with some people, I think Elcodi will continue with current PHP dependency, 5.4.

The reasons are many indeed, and all of them are so far from my point of view.

* Because Elcodi already works with current version (Like @xphere says, but is not 5.3 but 5.4... anyway, I think his arguments are right), we should not remove this possibility completely.
* Because we don't have (and surely need) any feature from >5.4. We chose 5.4 because of Traits, but like @javiereguiluz says, that's it...
* Because one thing is how PHP evolves and the other one is how the world does.

Regarding to this last point, this does not mean that we will focus on PHP 5.4 because it has no sense. if the time comes when we need some PHP>5.4 feature, then we will discuss if this upgrade has sense, our users are ready for that and if we really can do that.

Until now, we will push as much as possible for new PHP versions and all our code will be validated for  >=5.4, including `hhvm` and `php7`.
