### ISSUE TITLE
[RFC] [Payment] Add cart in the Payment Collector event

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#893]
- [x] Add the cart object and getter in the collector (https://github.com/elcodi/elcodi/pull/923)
- [x] Add the cart object in the PaymentEventDispatcher (https://github.com/elcodi/elcodi/pull/923)
- [x] Add the cart object in the PaymentWrapper (https://github.com/elcodi/elcodi/pull/923)
- [x] Update Bamboo for Cart addition (https://github.com/elcodi/bamboo/pull/595)
- [x] Update documentation (https://github.com/elcodi/docs/pull/95)

This issue introduces a question I would like to discuss.

* Do you think that a package event should be **`final`**?

Introducing the final specification, you are closing this class for extension.
What do you think?

Even if this package is *semver*, and because the project is not used that much nor used for overwriting, this is something I have in mind.

**Comment by mmoreram** [comment]
* Update the documentation as well

**Comment by sergigp** [comment]
IMHO all classes should be final by default

**Comment by mmoreram** [comment]
@sergigp and then, how you extend a class functionality, by decorating it?

**Comment by sergigp** [comment]
you can decorate without extend, remember the OCP. But in this case, a domain event, i can't think in one single case when you want to extend it... Extension is about specialitzacion, not about reutilisation and a domain event should be specific enough to avoid extension.

With this i'm not saying that ALL classes should be final, of course there are cases when extension is a valid solution.

**Comment by mmoreram** [comment]
@sergigp you're right.

Very interesting. The good point about defining all classes as final is that you protect all your protected methods from the API... and reducing the API layer, for an open source project, always is great news :)

I'll think about it.
Thanks!

**Comment by EmanueleMinotto** [comment]
Not sure if I'm following the discussion correctly (sorry in this case), anyway I'll ask it: if I need to specify an event able to collect/extract cards only methods (debit or credit), is it an extension of the `PaymentCollectionEvent` or a decoration?

Why should I use it? A use case could be to check if the user can be refunded by automatic payments.

**Comment by javiereguiluz** [comment]
@mmoreram don't forget to check out if any successful Open-Source PHP application follows this practice and if any comparable project (Sylius, DrupalCommerce, PrestaShop, Magento, etc.) follows it.

For example, Symfony creator rejected this idea very recently: https://github.com/symfony/symfony/issues/15233

**Comment by mmoreram** [comment]
@javiereguiluz I see.

I like to see other implementations from other successful OS PHP apps (let me consider Elcodi a successful open source PHP app... XD), but as a project lead I need to understand why some practices are done and why some others not. Considering doing something because other projects do, is a bad practice.

Anyway, I can understand that Symfony3 is not going to do that change... would mean a gorgeous BC Break! And Symfony is very far from being a 100% theoretical project.

Thanks for the tip! ^^

**Comment by unkind** [comment]
> @mmoreram don't forget to check out if any successful Open-Source PHP application follows this practice and if any comparable project (Sylius, DrupalCommerce, PrestaShop, Magento, etc.) follows it.

I wouldn't make decision because somebody doesn't follow the practice. Success and good code often don't correlate at all.

> For example, Symfony creator rejected this idea very recently: symfony/symfony#15233

Looks like he didn't reject it completely.

By the way, Behat 3 has `final` classes by default.

**Comment by javiereguiluz** [comment]
> I wouldn't make decision because somebody doesn't follow the practice. Success and good code often don't correlate at all.

I couldn't agree more with the last part of the sentence. If I'm right, Elcodi wants to be successful/popular, so it's clear what is has to do.

**Comment by unkind** [comment]
> I couldn't agree more with the last part of the sentence. If I'm right, Elcodi wants to be successful/popular, so it's clear what it has to do.

It is? If you agree that there is no correlation, then `final` or not, it doesn't matter. No correlation.

**Comment by mmoreram** [comment]
> Elcodi wants to be successful/popular

@javiereguiluz Yes, but only because it is a useful project, not only for final users but for developers. Elcodi aims to be a good solution based on a well architecture, thought for being used by the best PHP developers in the world.

Said that, this project will never take a decision because other projects do. Each decision will be analyzed and talked as many times as needed. Of course, other projects decisions will help us showing other points of view.

About this Issue, I don't have yet any comment. I will continue informing myself about this.

**Comment by mmoreram** [comment]
I have added the issue [Add final in all events](https://github.com/elcodi/elcodi/issues/921) for next version 2.0 (Major version, BC Break)
