### ISSUE TITLE
StoreNotFoundException comming after installation .

### ISSUE THREAD

**Issue by ajeetvarma** [elcodi/elcodi#933]
I follow the following link as below
 
$ php composer.phar create-project elcodi/bamboo youcreate -sdev
$ cd bamboo/
$ php app/console elcodi:install

$ php app/console server:run

and after installation complete when i run in browser as "localhost:8000"error come as 

   "StoreNotFoundException in StoreWrapper.php line 72: 
        Store not found."

I do't know what i m doing wrong , please give me idea about this ..

Thanks a lot in advance !!

**Comment by mmoreram** [comment]
Hi there @ajeetvarma 

Thanks for that feedback :)

When you do the `php app/console elcodi:install`, everything goes as expected?
This happens because the project doesn't find any store in DDBB, and this is because the fixtures/migrations are not working properly.

Can you check that please?

Thanks :)

**Comment by ajeetvarma** [comment]
Thanks a lot for reply., 

 yes After downloading the package when starting installation , after migration(database), at plugin installation time it is giving error like this that "Store Not Found .."
Then It is problem of migration or installation ? Then please give any solution ..



Once Again Thanks in Advance ..

**Comment by EmanueleMinotto** [comment]
@ajeetvarma seems that you're having a problem before the plugins installation and probably this isn't the right place to fix it in a fast way, click the button below to join the official chat, where a support can be provided directly :)

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/elcodi/elcodi?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by ajeetvarma** [comment]
Actually it was my installation problem and not i have fixed it, Thanks a lot for your great help ..
