### ISSUE TITLE
Add prefer-lowest to keep testing Symfony ^2.7

### ISSUE THREAD

**Issue by mmoreram** [elcodi/elcodi#985]

**Comment by mmoreram** [comment]
Should we duplicate the matrix?
Should we add a new line with an specific PHP version with `--prefer-lowest`?

**Comment by EmanueleMinotto** [comment]
Imo currently there should be 2 values for `COMPOSER_OPTIONS`:
* `install` <- max range
* `update --prefer-lowest` <- min range
