### ISSUE TITLE
CartLine shouldn't be indipendent

### ISSUE THREAD

**Issue by EmanueleMinotto** [elcodi/elcodi#993]
The entity `Elcodi\Component\Cart\Entity\CartLine` shouldn't be indipendent because it's based on the `Elcodi\Component\Cart\Entity\Traits\PurchasableWrapperTrait::$quantity` (by default `0`).

A solution could be to initialize the `$quantity = 1` making the assumption that there's by default this minimum number of purchasables?

**Comment by mmoreram** [comment]
Can you explain a little bit more this issue?

**Comment by mmoreram** [comment]
ping @EmanueleMinotto 

Otherwise, please close this :)

**Comment by EmanueleMinotto** [comment]
Not so much important, closing.
