### ISSUE TITLE
Strict User's gender value

### ISSUE THREAD

**Issue by EmanueleMinotto** [elcodi/elcodi#999]
Currently the user's gender (both admin or normal user) can be everything because it's based on integers: https://github.com/elcodi/elcodi/blob/master/src/Elcodi/Component/User/Entity/Abstracts/AbstractUser.php#L170

Its value should be more strict.

**Comment by mmoreram** [comment]
@EmanueleMinotto for example?

**Comment by EmanueleMinotto** [comment]
I like a lot this approach: https://github.com/puli/cli/pull/23#discussion_r44212816

We could still use the integer (I don't know, maybe in future to add a "I don't want to say my sex"...) but using constants associated to integers different developers and data can't do mistakes.
What do you think?

**Comment by mmoreram** [comment]
Can you tell me what sex values we should add? XD

**Comment by EmanueleMinotto** [comment]
afaik there are only two in this world XD so imo something like this could be used:
* `const UNDEFINED = 0`
* `const MALE = 1`
* `const FEMALE = 2`

So the final developer must only use `setGender(User::MALE)`, more easy to understand than `setGender(1)`.

Why the undefined? Some users could decide to not show their sex, so this possibility is available for them.

This could also be useful for filter based on bitmasks, for example:
* unisex dresses: `User::MALE | User::FEMALE`
* what did the admin forget to mark: `User::UNDEFINED`

**Comment by mmoreram** [comment]
@EmanueleMinotto okay then :D

**Comment by mmoreram** [comment]
@EmanueleMinotto could you please address this?

**Comment by EmanueleMinotto** [comment]
@mmoreram sure, I'll do it asap

**Comment by mmoreram** [comment]
Thanks dude :D
